name: Ink and Feet
favicon: null
layout_spectrum: 0.8052493194118142
typography_spectrum: 0.10029293247498572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6548885360825807
  lightness: 0.5900596315041184
  saturation: 0.300967839313671
  rhythmicContrast: 0.6861991013865918
purpose: []
